<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>0.1.0.0</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ManifestCertificateThumbprint>312A79631B5955AFEFE2D1140AEB2FB828EBD5B7</ManifestCertificateThumbprint>
    <ManifestKeyFile>GCSetComputerSettings_TemporaryKey.pfx</ManifestKeyFile>
    <GenerateManifests>false</GenerateManifests>
    <SignManifests>true</SignManifests>
    <ApplicationIcon>GC.ico</ApplicationIcon>
    <StartupObject>GCSetComputerSettings.Program</StartupObject>
    <TargetZone>LocalIntranet</TargetZone>
    <Copyright>Copyright ©  2021</Copyright>
    <Title>GCSetComputerSettings</Title>
    <Description>GitHub : https://github.com/SebGTx/GameserverControl</Description>
    <PackageProjectUrl>https://github.com/SebGTx/GameserverControl</PackageProjectUrl>
    <PackageIcon>GC_128x128.png</PackageIcon>
    <RepositoryUrl>https://github.com/SebGTx/GameserverControl</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>$([System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm"))</Version>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>embedded</DebugType>
    <OutputPath>..\Release\</OutputPath>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.7.2">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.7.2 %28x86 et x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="GC.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\GameserverControl\Resources\GC_128x128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>